# 1. Data Filtering

In [ ]:
# 595. Big Countries
import pandas as pd

def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    world.drop(
        labels = ["continent", "gdp"],
        axis = 1,
        inplace = True
    )

    return world[(world["area"] >= 3000000) | (world["population"] >= 25000000)]

In [ ]:
# 1757. Recyclable and Low Fat Products
import pandas as pd

def find_products(products: pd.DataFrame) -> pd.DataFrame:

    return products[(products["low_fats"] == "Y") & (products["recyclable"] == "Y")].drop(labels = ["low_fats", "recyclable"], axis = 1)

In [ ]:
# 83. Customers Who Never Order
import pandas as pd

def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:

    df_result: pd.DataFrame = (
        customers
        .rename(
            columns = {
                "id" : "customerId",
                "name" : "Customers"
            }
        )
        .merge(
            right = orders,
            how = "left",
            on = "customerId"
        )
    )

    return df_result[df_result["id"].isna()].drop(labels = ["customerId", "id"], axis = 1)

In [ ]:
# 1148. Article Views I
def article_views(views: pd.DataFrame) -> pd.DataFrame:

    views.drop(labels = ["view_date", "article_id"], axis = 1, inplace = True)
    views.drop_duplicates(inplace = True)

    return (
        views[views["author_id"] == views["viewer_id"]]
        .drop(
            labels = "viewer_id",
            axis = 1
        )
        .rename(
            columns = {
                "author_id" : "id"
            }
        )
        .sort_values(
            by = "id",
            ascending = True
        )
    )

# 2. String Methods

In [ ]:
# 1683. Invalid Tweets
import pandas as pd

def invalid_tweets(tweets: pd.DataFrame) -> pd.DataFrame:

    tweets["len"] = [len(content) for content in tweets["content"]]

    return (
        tweets[tweets["len"] > 15]
        .drop(
            labels = [
                "content",
                "len"
            ],
            axis = 1
        )
    )

In [ ]:
# 1873. Calculate Special Bonus
import pandas as pd

def calculate_special_bonus(employees: pd.DataFrame) -> pd.DataFrame:

    employees["bonus"] = [
        salary if (name[0] != "M") and (id % 2 != 0) else 0

        for name, salary, id in zip(
            employees["name"],
            employees["salary"],
            employees["employee_id"]
        )
    ]

    return employees[["employee_id", "bonus"]].sort_values(
        by = "employee_id",
        ascending = True
    )

In [ ]:
# 1667. Fix Names in a Table
import pandas as pd

def fix_names(users: pd.DataFrame) -> pd.DataFrame:
    users["name"] = [
        name if name[0] in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0] else name.title()
        for name in users["name"]
    ]

    return users.sort_values(by = "user_id", ascending = True)

In [ ]:
# 1517. Find Users With Valid E-Mails
import re
import pandas as pd

def valid_emails(users: pd.DataFrame) -> pd.DataFrame:
    
    users["is_valid"] = [
        "valid" if re.match(pattern = r"^[a-zA-Z][a-zA-Z0-9._-]*@leetcode[.]com", string = mail) else "invalid"
        
        for mail in users["mail"]
    ]
    
    return users[users['is_valid'] == 'valid'].drop(labels = 'is_valid', axis = 1)

In [ ]:
# 1527. Patients With a Condition
import pandas as pd

def find_patients(patients: pd.DataFrame) -> pd.DataFrame:
    
    patients["is_diabet"] = False
    
    for idx, string_with_conditions in enumerate(iterable = patients["conditions"]):
        for condition in string_with_conditions.split(" "):
            if condition[:5].lower() == "diab1":
                patients.loc[idx, "is_diabet"] = True
            
            else:
                continue
    
    return patients[patients["is_diabet"] == True].drop(labels = "is_diabet", axis = 1)

# 3. Data Manipulation

In [ ]:
# 177. Nth Highest Salary
import pandas as pd

def nth_highest_salary(employee: pd.DataFrame, N: int) -> pd.DataFrame:

    if len(list(set(employee["salary"]))) < N:
        
        return pd.DataFrame(
            data = [None],
            columns = ["SecondHighestSalary"]
        )

    elif len(list(set(employee["salary"]))) == 1:
        
        return pd.DataFrame(
            data = [sorted(list(set(employee["salary"])))[0]],
            columns = ["SecondHighestSalary"]
        )
            
    else:

        return pd.DataFrame(
            data = [sorted(list(set(employee["salary"])))[-N]],
            columns = ["SecondHighestSalary"]
        )

In [ ]:
# 176. Second Highest Salary
import pandas as pd

def second_highest_salary(employee: pd.DataFrame) -> pd.DataFrame:

    if len(list(set(employee["salary"]))) <= 1:
        
        return pd.DataFrame(
            data = [None],
            columns = ["SecondHighestSalary"]
        )
    
    else:

        return pd.DataFrame(
            data = [sorted(list(set(employee["salary"])))[-2]],
            columns = ["SecondHighestSalary"]
        )

In [ ]:
# 184. Department Highest Salary
import pandas as pd

def department_highest_salary(employee: pd.DataFrame, department: pd.DataFrame) -> pd.DataFrame:

    employee = (
        employee
        .merge(
            right = (
                department
                .rename(
                    columns = {
                        "id" : "departmentId",
                        "name" : "Department"
                    }
                )
            ),
            how = "inner",
            on = "departmentId"
        )
    )

    temp_df: pd.DataFrame = (
        employee
        .groupby(
            by = [
                "Department",
                "departmentId"
            ]
        )
        .aggregate(
            {
                "salary" : "max"
            }
        )
        .reset_index()
        .merge(
            right = employee[
                [
                    "name",
                    "salary",
                    "departmentId"
                ]
            ],
            how = "inner",
            on = [
                "departmentId",
                "salary"
            ]
        )
        .rename(
            columns = {
                "name" : "Employee",
                "salary" : "Salary"
            }
        )
    )

    return temp_df[
        [
            "Department",
            "Employee",
            "Salary"
        ]
    ]

In [ ]:
# 178. Rank Scores
import pandas as pd

def order_scores(scores: pd.DataFrame) -> pd.DataFrame:

    scores.drop(
        labels = "id",
        axis = 1,
        inplace = True
    )

    scores["rank"] = scores.rank(method = "dense", ascending = False)

    return scores.sort_values(by = "score", ascending = False)

In [ ]:
# 196. Delete Duplicate Emails
import pandas as pd

# Modify Person in place
def delete_duplicate_emails(person: pd.DataFrame) -> None:

    person.sort_values(
        by = "id",
        ascending = True,
        inplace = True
    )
    
    person.drop_duplicates(
        subset = "email",
        inplace = True
    )

In [ ]:
# 1795. Rearrange Products Table
import pandas as pd

def rearrange_products_table(products: pd.DataFrame) -> pd.DataFrame:

    return (
        products
        .set_index(keys = "product_id")
        .stack()
        .reset_index()
        .rename(
            columns = {
                "level_1": "store", 0 : "price"
            }
        )
    )

# 4. Statistics

In [ ]:
# 2082. The Number of Rich Customers
import pandas as pd

def count_rich_customers(store: pd.DataFrame) -> pd.DataFrame:

    return pd.DataFrame(data = [store[store["amount"] > 500]["customer_id"].nunique()], columns = ["rich_count"])

In [ ]:
# 1173. Immediate Food Delivery I
import pandas as pd

def food_delivery(delivery: pd.DataFrame) -> pd.DataFrame:

    delivery["time"] = [
        1 if order == deliver else 0

        for order, deliver in zip(
            delivery["order_date"],
            delivery["customer_pref_delivery_date"]
        )
    ]

    immediate_count = list(delivery["time"]).count(1)
    total = len(delivery)

    return pd.DataFrame(data = zip([round(number = immediate_count / total * 100, ndigit = 2)]), columns = ["immediate_percentage"])

In [ ]:
# 1907. Count Salary Categories
import pandas as pd

def count_salary_categories(accounts: pd.DataFrame) -> pd.DataFrame:

    low_salary = 0
    average_salary = 0
    high_salary = 0

    for income in accounts['income']:
        if income < 20000:
            low_salary += 1
        
        elif 20000 <= income <= 50000:
            average_salary += 1
        
        else:
            high_salary += 1
        
    return (
        pd.DataFrame(
            data = zip(
                [
                    "Low Salary",
                    "Average Salary",
                    "High Salary"
                ],
                [
                    low_salary,
                    average_salary,
                    high_salary
                ]
            ),
            columns = [
                "category",
                "accounts_count"
            ]
        )
        .sort_values(
            by = "accounts_count",
            ascending = False
        )
    )

# 5. Data Aggregation

In [ ]:
# 1741. Find Total Time Spent by Each Employee
import pandas as pd

def total_time(employees: pd.DataFrame) -> pd.DataFrame:

    employees["total_time"] = [
        end - start

        for start, end in zip(
            employees["in_time"],
            employees["out_time"]
        )
    ]

    return (
        employees
        .groupby(
            by = [
                "event_day",
                "emp_id"
            ]
        )
        .aggregate(
            {
                "total_time" : "sum"
            }
        )
        .reset_index()
        .rename(
            columns = {
                "event_day" : "day"
            }
        )
    )

In [ ]:
# 511. Game Play Analysis I
import pandas as pd

def game_analysis(activity: pd.DataFrame) -> pd.DataFrame:

    return (
        activity
        .sort_values(
            by = "event_date",
            ascending = True
        )
        .drop_duplicates(
            subset = "player_id"
        )
        .drop(
            labels = [
                "device_id",
                "games_played"
            ],
            axis = 1
        )
        .rename(
            columns = {
                "event_date" : "first_login"
            }
        )
    )

In [ ]:
# 2356. Number of Unique Subjects Taught by Each Teacher
import pandas as pd

def count_unique_subjects(teacher: pd.DataFrame) -> pd.DataFrame:

    return (
        teacher
        .groupby(by = "teacher_id")
        .aggregate(arg = {
            "subject_id" : "nunique"
            }
        )
        .reset_index()
        .rename(
            columns = {
                "subject_id" : "cnt"
            }
        )
    )

In [ ]:
# 596. Classes More Than 5 Students
import pandas as pd

def find_classes(courses: pd.DataFrame) -> pd.DataFrame:

    return (
        courses
        .groupby(by = "class")
        .aggregate(
            {
                "student" : "count"
            }
        )
        .reset_index()
        .query(expr = "student >= 5")
        .drop(
            labels = "student",
            axis = 1
        )
    )

In [ ]:
# 586. Customer Placing the Largest Number of Orders
import pandas as pd

def largest_orders(orders: pd.DataFrame) -> pd.DataFrame:

    temp_df: pd.DataFrame = (
        orders
        .groupby(by = "customer_number")
        .aggregate(
            {
                "order_number" : "count"
            }
        )
        .reset_index()
        .sort_values(
            by = "order_number",
            ascending = False
        )
    )

    return (
        temp_df[temp_df["order_number"] == temp_df["order_number"].max()]
        .drop(
            labels = "order_number",
            axis = 1
        )
    )

In [ ]:
# 1484. Group Sold Products By The Date
import pandas as pd

def categorize_products(activities: pd.DataFrame) -> pd.DataFrame:
    
    activities = (
        pd.DataFrame(
            data = (
                activities
                .groupby(
                    by = "sell_date"
                )["product"]
                .apply(
                    func = set
                )
            )
            .reset_index()
            .rename(
                columns = {
                    "product" : "products"
                }
            )
        )
    
    activities['products'] = (
        activities['products']
        .apply(
            func = lambda x: sorted(list(x))
        )
    )
    
    activities["num_sold"] = [len(product) for product in activities["products"]]
    
    activities['products'] = (
        activities['products']
        .apply(
            func = ','.join
        )
    )

    return activities[
        [
            "sell_date",
            "num_sold",
            "products"
        ]
    ]

In [ ]:
# 1693. Daily Leads and Partners
import pandas as pd

def daily_leads_and_partners(daily_sales: pd.DataFrame) -> pd.DataFrame:
    
    return (
        daily_sales
        .groupby(
            by = [
                "date_id",
                "make_name"
            ]
        )
        [
            [
                "lead_id",
                "partner_id"
            ]
        ]
        .apply("nunique")
        .reset_index()
        .rename(
            columns = {
                "lead_id" : "unique_leads",
                "partner_id" : "unique_partners"
            }
        )
    )

# 6. Data Integration

In [ ]:
# 1050. Actors and Directors Who Cooperated At Least Three Times
import pandas as pd

def actors_and_directors(actor_director: pd.DataFrame) -> pd.DataFrame:

    return (
        actor_director
        .value_counts(
            subset = [
                "actor_id",
                "director_id"
            ]
        )
        .reset_index()
        .query(
            expr = "count >= 3"
        )
        .drop(
            labels = "count",
            axis = 1
        )
    )

In [ ]:
# 1378. Replace Employee ID With The Unique Identifier
import pandas as pd

def replace_employee_id(employees: pd.DataFrame, employee_uni: pd.DataFrame) -> pd.DataFrame:

    return (
        employees
        .merge(
            right = employee_uni,
            how = "left",
            on = "id"
        )
        .drop(
            labels = "id",
            axis = 1
        )
    )

In [ ]:
# 1280. Students and Examinations
import pandas as pd

def students_and_examinations(students: pd.DataFrame, subjects: pd.DataFrame, examinations: pd.DataFrame) -> pd.DataFrame:
    
    if len(students) == 0 or len(subjects) == 0 or len(examinations) == 0:
        return pd.DataFrame(
            columns = [
                "student_id",
                "student_name",
                "subject_name",
                "attended_exams"
            ]
        )

    students["key"] = None
    subjects["key"] = None

    temp_df: pd.DataFrame = (
        students
        .merge(
            right = subjects,
            how = "outer",
            on = "key"
        )
        .merge(
            right = (
                students.merge(
                    right = examinations,
                    how = "left",
                    on = "student_id"
                )
                .value_counts(subset = ["student_id", "student_name", "subject_name"])
                .reset_index()
            ),
            how = "left",
            on = ["student_id", "student_name", "subject_name"]
        )
        .sort_values(
            by = ["student_id", "subject_name"],
            ascending = True
        )
        .rename(
            columns = {
                "count" : "attended_exams"
            }
        )
        .fillna(value = 0)
    )

    del temp_df["key"]

    return temp_df

In [ ]:
# 570. Managers with at Least 5 Direct Reports
import pandas as pd

def find_managers(employee: pd.DataFrame) -> pd.DataFrame:

    df_temp: pd.DataFrame = (
        pd.DataFrame(
            data = (
                employee
                .value_counts(
                    subset = "managerId"
                )
            )
            .reset_index()
        )
    )
    
    set_count_above_five: set = set(df_temp[df_temp["count"] >= 5]["managerId"])

    return pd.DataFrame(data = employee[employee["id"].isin(values = set_count_above_five)]["name"])

In [ ]:
# 607. Sales Person
import pandas as pd

def sales_person(sales_person: pd.DataFrame, company: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    
    df_merge: pd.DataFrame = (
        sales_person[["sales_id", "name"]]
        .merge(
            right = orders[["sales_id", "com_id"]],
            how = "left",
            on = "sales_id"
        )
        .merge(
            right = (
                company[["com_id", "name"]]
                .rename(
                    columns = {
                        "name" : "company_name"
                    }
                )
            ),
            how = "left",
            on = "com_id"
        )
    )
    
    red_sales = set(df_merge[df_merge["company_name"] == "RED"]["name"])

    return (
        pd.DataFrame(data = df_merge[~df_merge["name"].isin(values = red_sales)]["name"])
        .drop_duplicates(
            subset = "name"
        )
    )